//@flow
export const CREATION_FORM_STATUS_REQUEST = 'CREATION_FORM_STATUS_REQUEST';
export const CREATION_FORM_STATUS_FAILURE = 'CREATION_FORM_STATUS_FAILURE';
export const CREATION_FORM_STATUS_SUCCESS = 'CREATION_FORM_STATUS_SUCCESS';

export const SAVE_CREATION_FORM_DATA = 'SAVE_CREATION_FORM_DATA';
