//@flow
export const REGISTRATION_FORM_STATUS_REQUEST = 'REGISTRATION_FORM_STATUS_REQUEST';
export const REGISTRATION_FORM_STATUS_FAILURE = 'REGISTRATION_FORM_STATUS_FAILURE';
export const REGISTRATION_FORM_STATUS_SUCCESS = 'REGISTRATION_FORM_STATUS_SUCCESS';

export const SAVE_REGISTRATION_FORM_DATA = 'SAVE_REGISTRATION_FORM_DATA';
